import { promises as fs } from 'fs';
import path from 'path';
import { NextResponse } from 'next/server';
import { headers } from 'next/headers';

export async function POST(request: Request) {
  try {
    const data = await request.json();
    if (!data || typeof data !== 'object') {
      return NextResponse.json({ error: 'Invalid payload' }, { status: 400 });
    }

    const headersList = await headers();
    const ip = headersList.get('x-forwarded-for') || headersList.get('x-real-ip') || 'unknown';
    const timestamp = new Date().toISOString();
    const logEntry = {
      timestamp,
      user: 'admin',
      ip,
      action: 'updated',
      details: 'Portfolio configuration updated via admin panel'
    };

    // Prepare paths
    const configPath = path.join(process.cwd(), 'src', 'config', 'portfolio.config.ts');
    const logsDir = path.join(process.cwd(), 'src', 'data');
    const logsPath = path.join(logsDir, 'admin_logs.json');

    // Ensure directories exist
    await fs.mkdir(path.dirname(configPath), { recursive: true });
    await fs.mkdir(logsDir, { recursive: true });

    // Prepare the TypeScript file content
    const fileContent = `// 🎨 PORTFOLIO CONFIGURATION - AUTO-GENERATED BY ADMIN PANEL
export const portfolioConfig = ${JSON.stringify(data, null, 2)};
`;

    // Write the new config
    await fs.writeFile(configPath, fileContent, 'utf8');

    // Handle Logging
    let currentLogs = [];
    try {
      const logsRaw = await fs.readFile(logsPath, 'utf8');
      currentLogs = JSON.parse(logsRaw);
    } catch (e) {
      // File doesn't exist yet or is invalid
    }
    currentLogs.push(logEntry);
    await fs.writeFile(logsPath, JSON.stringify(currentLogs, null, 2), 'utf8');

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (err) {
    console.error('Error saving portfolio data:', err);
    return NextResponse.json({ error: (err as any)?.message ?? 'unknown' }, { status: 500 });
  }
}
