// src/app/api/admin/save/route.ts
import { promises as fs } from 'fs';
import path from 'path';
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const data = await request.json();
    if (!data || typeof data !== 'object') {
      return NextResponse.json({ error: 'Invalid payload' }, { status: 400 });
    }

    // Prepare the TypeScript file content
    const fileContent = `// 🎨 PORTFOLIO CONFIGURATION - AUTO-GENERATED BY ADMIN PANEL
export const portfolioConfig = ${JSON.stringify(data, null, 2)};
`;

    const filePath = path.join(process.cwd(), 'src', 'config', 'portfolio.config.ts');
    
    // Ensure the directory exists (it should, but safety first)
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    
    // Write the new config
    await fs.writeFile(filePath, fileContent, 'utf8');

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (err) {
    console.error('Error saving portfolio data:', err);
    return NextResponse.json({ error: (err as any)?.message ?? 'unknown' }, { status: 500 });
  }
}
